-- INSERT INTO TODO(ID, TITLE, CONTENT, IS_CHECK) VALUES ('1', '어제부터시작', '금연일지', 'N');
-- INSERT INTO TODO(ID, TITLE, CONTENT, IS_CHECK) VALUES ('2', '오늘부터시작', '금연일지', 'N');
-- INSERT INTO TODO(ID, TITLE, CONTENT, IS_CHECK) VALUES ('3', '내일부터시작', '금연일지', 'N');
-- INSERT INTO TODO(ID, TITLE, CONTENT, IS_CHECK) VALUES ('4', '내년부터시작', '금연일지', 'N');